app/urls.py
from django.contrib import admin
from django.urls import path, include

from views import (
    HomeView,
    TermsView,
    PrivacyView,
    SupportView,
    SiteMapView,
    RobotsView
)

urlpatterns = [
    path(
        route='',
        view=HomeView.as_view(),
        name="home"
    ),
    path(
        route='terms-of-service/',
        view=TermsView.as_view(),
        name="tos"
    ),
    path(
        route='privacy-policy/',
        view=PrivacyView.as_view(),
        name="privacy"
    ),
    path(
        route='support/',
        view=SupportView.as_view(),
        name="support"
    ),
    path(
        route='sitemap.xml',
        view=SiteMapView.as_view(),
        name="sitemap"
    ),
    path(
        route='robots.txt',
        view=RobotsView.as_view(),
        name="robots"
    ),
    path(
        route="users/",
        view=include(
            ('users.urls', 'users'),
            namespace="users"
        )
    ),
    path(
        route='stripe/',
        view=include(
            "djstripe.urls",
            namespace="djstripe"
        ),
    ),
    path(
        route='auth/',
        view=include('allauth.urls')
    ),
    path(
        route='admin/',
        view=admin.site.urls,
    ),
]

app/users/urls.py
from django.urls import path

from .views import (
    DashboardView,
    AccountView,
    PasswordChangeView,
    BillingView,
    CheckoutView,
    SubscriptionView,
EmailChangeView,
)

urlpatterns = [
    path(
        route='',
        view=DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        route='account/',
        view=AccountView.as_view(),
        name="account"
    ),
    path(
        route='account/change-password/',
        view=PasswordChangeView.as_view(),
        name="change-password"
    ),
    path(
        route='account/change-email/',
        view=EmailChangeView.as_view(),
        name="change-email"
    ),
    path(
        route='subscription/',
        view=SubscriptionView.as_view(),
        name="subscription"
    ),
    path(
        route='billing/',
        view=BillingView.as_view(),
        name='billing'
    ),
    path(
        route='checkout/',
        view=CheckoutView.as_view(),
        name="checkout"
    ),
]

app/users/models.py
from logging import getLogger

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.functional import cached_property
from djstripe.exceptions import MultipleSubscriptionException
from djstripe.models import Customer, Plan
from djstripe.models import Subscription
from stripe.error import AuthenticationError

from users.email import subscribe_to_mailing_list, unsubscribe_from_mailing_list

logger = getLogger(__name__)


class User(AbstractUser):
    newsletter = models.BooleanField(
        default=True
    )

    @property
    def bypassing_stripe(self):
        """Checks if BYPASS_STRIPE is set to True in settings"""
        return settings.BYPASS_STRIPE

    @cached_property
    def customer(self):
        try:
            customer, _ = Customer.get_or_create(self)
            return customer
        except AuthenticationError as e:
            # if we are bypassing stripe, we swallow the exception and
            # emit a warning instead. This allows us to develop the app
            # without caring about setting up stripe for every development
            # environment
            if settings.BYPASS_STRIPE:
                logger.warning(
                    "Warning: You are using an invalid Stripe API key. Since BYPASS_STRIPE is set to True, this "
                    "error is ignored. To test your Stripe integration, make sure to set BYPASS_STRIPE to False."
                )
                return None
            raise e

    @cached_property
    def has_active_subscription(self):
        """Checks if a user has an active subscription."""
        try:
            return self.customer.subscription is not None
        except MultipleSubscriptionException:
            return True
        except AttributeError as e:
            # if BYPASS_STRIPE is set to True, our customer object has no
            # subscription (it is None). Setting BYPASS_STRIPE to True
            # allows us to test the app, without setting up Stripe for
            # every development environment
            if settings.BYPASS_STRIPE:
                return True
            raise e

    @cached_property
    def invoices(self):
        return self.customer.invoices.all()

    @property
    def is_trialling(self):
        return not self.has_active_subscription and self.trial_ends_at > timezone.now()

    @property
    def trial_ends_at(self):
        return self.date_joined + timezone.timedelta(days=settings.TRIAL_DAYS)

    @cached_property
    def plan(self):
        # if BYPASS_STRIPE is set to True, we simply return the trial
        # plan. This allows us to test the app without setting up
        # stripe for every development environment
        if settings.BYPASS_STRIPE:
            logger.warning(
                "Warning: Bypassing Stripe integration since BYPASS_STRIPE is set to True. \n"
                "To test your Stripe integration, make sure to set up BYPASS_STRIPE to False.\n"
                "Learn more at: https://getlaunchr.com/docs/payments/"
            )
            return settings.PLANS[settings.TRIAL_PLAN_KEY]
        if self.stripe_plan:
            return self.get_plan_by_stripe_id(
                self.stripe_plan.id
            )
        return None

    @cached_property
    def stripe_plan(self):
        if self.has_active_subscription:
            try:
                return self.customer.subscription.plan
            except MultipleSubscriptionException:
                return self.customer.subscriptions.latest().plan
        if self.is_trialling:
            return Plan.objects.get(
                id=self.get_stripe_plan_id_by_key(settings.TRIAL_PLAN_KEY)
            )
        return None

    def can_use_feature(self, feature_key):
        if self.plan:
            for feature in self.plan.get('features', []):
                if feature['key'] == feature_key:
                    return feature['enabled']
            plan_uuid = self.get_plan_by_stripe_id(self.plan.id)
            raise ImproperlyConfigured(
                f"Unable to find the feature with feature_key '{feature_key}' for the plan \n"
                f"with the uuid '{plan_uuid}'. Make sure to add it to the features list in \n"
                f"your settings.\n"
                f"See: https://getlaunchr.com/docs/subscriptions/#can_use_feature"
            )
        return False

    @staticmethod
    def get_plan_by_stripe_id(stripe_id):
        for plan in settings.PLANS.values():
            if plan['stripe_id'] == stripe_id:
                return plan
        raise ImproperlyConfigured(
            f"Unable to find a configured plan for the stripe_id '{stripe_id}'.\n"
            f"Make sure to add the 'stripe_id' to one of your plans in your settings.\n"
            f"See: https://getlaunchr.com/docs/subscriptions/#get_plan_by_stripe_id"
        )

    @staticmethod
    def get_stripe_plan_id_by_key(plan_key):
        stripe_id = settings.PLANS.get(plan_key, {}).get('stripe_id', None)
        if not stripe_id:
            raise ImproperlyConfigured(
                f"Unable to get the stripe_id for the plan with the key '{plan_key}'.\n"
                f"Make sure to set the 'stripe_id' in your settings correctly.\n"
                f"See: https://getlaunchr.com/docs/subscriptions/#get_stripe_plan_id_by_key"
            )
        return stripe_id

    def save(self, *args, **kwargs):
        """
        This method overrides the default users save method to
        subscribe/unsubscribe the user from the mailing list
        """
        # check if this is a new user
        if self.pk is not None:
            # get the old record for this user, prior to the save
            old = User.objects.get(pk=self.pk)
            # if the user was subscribed to the newsletter but
            # is no longer interested in it (or vice versa),
            # change it
            if self.newsletter != old.newsletter:
                if self.newsletter:
                    subscribe_to_mailing_list(
                        email=self.email,
                        first=self.first_name,
                        last=self.last_name
                    )
                else:
                    unsubscribe_from_mailing_list(
                        email=self.email
                    )
        return super(User, self).save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user(sender, created, instance: User, **kwargs):
    """
    Signal that gets triggered once a new user object is created.
    It is used to subscribe users to the mailing list.
    """
    if created and instance.newsletter:
        subscribe_to_mailing_list(
            email=instance.email,
            first=instance.first_name,
            last=instance.last_name
        )

app/users/forms.py
from allauth.account.forms import SignupForm
from django import forms

from users.models import User


class CustomSignupForm(SignupForm):
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        return user


class AccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'newsletter',
        )

app/users/views.py
import json

import stripe
from allauth.account.views import (
    PasswordChangeView as AllauthPasswordChangeView,
    EmailView as AllauthEmailView,
)
from allauth.account.adapter import get_adapter
from allauth.account import signals
from allauth.account.models import EmailAddress
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, UpdateView
from djstripe.models import Customer
from users.forms import AccountForm
from users.email import subscribe_to_mailing_list, unsubscribe_from_mailing_list

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "users/dashboard.html"


class AccountView(LoginRequiredMixin, UpdateView):
    template_name = "users/account.html"
    form_class = AccountForm

    def get_success_url(self):
        return reverse("users:account")

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        data = super(AccountView, self).get_context_data(**kwargs)
        data['password_changed'] = bool(self.request.GET.get("password_changed", False))
        data['email_changed'] = bool(self.request.GET.get("email_changed", False))
        return data


class PasswordChangeView(AllauthPasswordChangeView):

    def get_success_url(self):
        return reverse("users:account") + "?password_changed=True"


class EmailChangeView(AllauthEmailView):

    def form_valid(self, form):
        # copying allauths form validation to be
        # as close to the original as possible.
        # we could remove the signals since we are not using them,
        # but I left them in if we need them at some point
        email_address = form.save(self.request)
        get_adapter(self.request).add_message(
            self.request,
            messages.INFO,
            "account/messages/" "email_confirmation_sent.txt",
            {"email": form.cleaned_data["email"]},
        )
        signals.email_added.send(
            sender=self.request.user.__class__,
            request=self.request,
            user=self.request.user,
            email_address=email_address,
        )
        # make the email address primary
        email_address.set_as_primary()
        # subscribe the user to the mailing list, if it is enabled
        if self.request.user.newsletter:
            subscribe_to_mailing_list(
                email=email_address.email,
                first=self.request.user.first_name,
                last=self.request.user.last_name
            )
        # get all old email addresses for this user and delete them
        # from the database and from the mailing list
        for email in EmailAddress.objects.filter(
            user=self.request.user
        ).exclude(
            pk=email_address.pk
        ):
            unsubscribe_from_mailing_list(
                email=email.email
            )
            email.delete()
        return super(EmailChangeView, self).form_valid(form)

    def get_success_url(self):
        # on a successfull email change, we are going to redirect
        # the user to the main account page
        return reverse("users:account") + "?email_changed=True"

    def post(self, request, *args, **kwargs):
        # overriding the default post method to disable all
        # the add/remove/send/primary actions here.
        # we are going to handle them in form_valid
        return super(AllauthEmailView, self).post(request, *args, **kwargs)


class SubscriptionView(LoginRequiredMixin, TemplateView):
    template_name = "users/subscription.html"


class BillingView(LoginRequiredMixin, UpdateView):

    def post(self, request, *args, **kwargs):
        url = self.request.POST.get("url", False)
        if not url:
            url = self.request.build_absolute_uri(settings.LOGIN_REDIRECT_URL)

        customer, created = Customer.get_or_create(request.user)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        response = stripe.billing_portal.Session.create(
            customer=customer.id,
            return_url=url,
        )
        return redirect(to=response.url, permanent=False)

    def get(self, request, *args, **kwargs):
        raise PermissionDenied


class CheckoutView(LoginRequiredMixin, UpdateView):

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        plan_id = data.get("priceId", False)

        if not plan_id:
            raise PermissionDenied

        customer, created = Customer.get_or_create(request.user)

        stripe.api_key = settings.STRIPE_SECRET_KEY

        url = f"{self.request.scheme}://{self.request.get_host()}/"
        session = stripe.checkout.Session.create(
            customer=customer.id,
            payment_method_types=['card'],
            line_items=[{
                'price': plan_id,
                'quantity': 1,
            }],
            mode='subscription',
            success_url=url,
            cancel_url=url,
        )
        return JsonResponse({"id": session['id']})

    def get(self, request, *args, **kwargs):
        raise PermissionDenied

app/templates/users/account.html
{% extends "users/base.html" %}

{% block title %}Account{% endblock %}

{% block content %}
  <h2 class="pt-3 pb-2">Personal</h2>
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <form method="POST" action="{% url 'users:account' %}">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="pb-4">
            <div class="text-danger" role="alert">
              {% for error in form.non_field_errors %}
                <div class="">{{ error }}</div>
              {% endfor %}
            </div>
          </div>
        {% endif %}

        <div class="row mb-3">
          <label class="col-sm-3 col-form-label">First Name</label>
          <div class="col-sm-9">
            <input name="first_name" value="{{ form.first_name.value }}" type="text" class="form-control {% if form.first_name.errors %}is-invalid{% endif %}">
            {% if form.first_name.errors %}
              <div class="invalid-feedback">
                {% for error in form.first_name.errors %}
                  {{ error|escape }}<br/>
                {% endfor %}
              </div>
            {% endif %}
          </div>
        </div>
        <div class="row mb-3">
          <label class="col-sm-3 col-form-label">Last Name</label>
          <div class="col-sm-9">
            <input name="last_name" value="{{ form.last_name.value }}" type="text" class="form-control {% if form.last_name.errors %}is-invalid{% endif %}">
            {% if form.last_name.errors %}
              <div class="invalid-feedback">
                {% for error in form.last_name.errors %}
                  {{ error|escape }}<br/>
                {% endfor %}
              </div>
            {% endif %}
          </div>
        </div>
        <div class="row mb-3">
          <label for="inputPassword3" class="col-sm-3 col-form-label">Newsletter</label>
          <div class="col-sm-9">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="newsletter" {% if form.newsletter.value %}checked{% endif %}>
              <label class="form-check-label">
                Get the Newsletter
              </label>
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-dark">Save</button>
      </form>
    </div>
    <div class="col-md-5 text-center">
      <div class="avatar-big bg-gradient text-white text-center mb-3">
        {{ user.email.0|upper }}
      </div>
      <br/>
      <span class="text-muted">{{ user.email }}</span>
    </div>
  </div>

  <h2 class="pt-5 pb-2">Account</h2>
  <div class="row">

    <div class="col-md-7">
      <div class="input-group mb-3">
        <label class="col-sm-3 col-form-label">Email</label>
        <input type="text" disabled class="form-control" value="{{ user.email }}">
        <a class="btn btn-dark" type="button" href="{% url "users:change-email" %}">Change</a>
      </div>
      {% if email_changed %}
        <div class="alert alert-success">
          The email has been changed
        </div>
      {% endif %}
      <div class="input-group mb-3">
        <label class="col-sm-3 col-form-label">Password</label>
        <input type="password" disabled class="form-control" value="redacted-redacted">
        <a class="btn btn-dark" type="button" href="{% url "users:change-password" %}">Edit</a>
      </div>
      {% if password_changed %}
        <div class="alert alert-success">
          The password has been changed
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

app/templates/users/base.html
{% extends 'base.html' %}
{% load static humanize %}

{% block body_class %}bg-light{% endblock %}

{% block main %}
  <header class="navbar navbar-expand-lg sticky-top bg-white p-0 navbar-dashboard">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url "users:dashboard" %}">
      <img height="50px" src="{% static "images/logo_white.png" %}"/>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 px-3">

        <li class="nav-item">
          <span class="nav-link">
            <strong>Plan</strong> {{ user.plan.name }} {% if user.is_trialling %}Trial{% endif %}
            <a href="{% url "users:subscription" %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg>
            </a>
          </span>
        </li>

      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="avatar bg-gradient text-white">
              {{ user.email.0|upper }}
            </div>
            {{ user.email }}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url "users:subscription" %}">Subscription</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url "users:account" %}">Account</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="{% url "account_logout" %}">Sign Out</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </header>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-3 col-lg-2 d-md-block bg-dark navbar-dark sidebar collapse">
        <div class="position-sticky pt-0 ">
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-2 mb-1 text-muted">
            <span>Something</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="8" x2="12" y2="16"></line>
                <line x1="8" y1="12" x2="16" y2="12"></line>
              </svg>
            </a>
          </h6>
          <ul class="nav flex-column ">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "users:dashboard" %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers">
                  <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                  <polyline points="2 17 12 22 22 17"></polyline>
                  <polyline points="2 12 12 17 22 12"></polyline>
                </svg>
                Dashboard
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

        {% block content %}{% endblock %}
      </main>
    </div>
  </div>
  <script src="https://js.stripe.com/v3/"></script>
  <script type="text/javascript">

    var createCheckoutSession = function (priceId) {
      return fetch("{% url 'users:checkout' %}", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": "{{ csrf_token }}",
        },
        body: JSON.stringify({
          priceId: priceId
        })
      }).then(function (result) {
        return result.json();
      });
    };
    var stripe = Stripe('{{ stripe_public_key }}');
    document.addEventListener("DOMContentLoaded", function () {
      document.querySelectorAll('.checkout').forEach(function (button) {
        button.addEventListener("click", function (evt) {
          createCheckoutSession(button.dataset.price).then(function (data) {
            // Call Stripe.js method to redirect to the new Checkout page
            stripe.redirectToCheckout({
              sessionId: data.id
            }).then(function (result) {
              if (result.error) {
                alert(result.error.message)
              }
            });
          });
        });
      });
    });

  </script>
{% endblock %}

app/templates/users/dashboard.html
{% extends "users/base.html" %}

{% block content %}
  <div class="bg-gradient" style="margin-left: -25px; margin-right: -25px;">
    <div class="row p-5">
      <div class="col-md-6">
        <div class="h5 text-white-50 pt-5">
          The heart of your app
        </div>
        <div class="h1 text-white pb-5">This is
          where<br/> the magic happens.
        </div>

      </div>
      <div class="col-md-6 text-center pt-3">
        <svg class="text-white" width="200" height="200" viewBox="0 0 200 200">
          <g transform="translate(100 100)">
            <path transform="translate(-50 -50)" fill="currentColor" d="M92.71,7.27L92.71,7.27c-9.71-9.69-25.46-9.69-35.18,0L50,14.79l-7.54-7.52C32.75-2.42,17-2.42,7.29,7.27v0 c-9.71,9.69-9.71,25.41,0,35.1L50,85l42.71-42.63C102.43,32.68,102.43,16.96,92.71,7.27z"></path>
            <animateTransform
                attributeName="transform"
                type="scale"
                values="1; 1.5; 1.25; 1.5; 1.5; 1;"
                dur="1s"
                repeatCount="indefinite"
                additive="sum">
            </animateTransform>
          </g>
        </svg>
      </div>
    </div>


  </div>
{% endblock %}

app/templates/users/subscription.html
{% extends "users/base.html" %}

{% block title %}Subscription{% endblock %}

{% block content %}
  {% if user.bypassing_stripe %}
    <div class="alert alert-warning mt-3">
      <p><strong>WARNING</strong></p>
      <p>
        You have set <strong>BYPASS_STRIPE</strong> to <strong>True</strong> in your settings file.</p>

      <p>This allows you to test your app without setting up Stripe for every development environment but
        also disables the Stripe integration. With <strong>BYPASS_STRIPE</strong> enabled, you won't be
        able to manage your subscription, or select one of the plans below.
      </p>
      <p>
        To set up stripe, please follow the docs at: <a target="_blank" href="https://getlaunchr.com/docs/payments/">
        https://getlaunchr.com/docs/payments/</a>
      </p>
    </div>
  {% endif %}
  <h2 class="pt-3 pb-3">Subscription</h2>
  {% if user.has_active_subscription %}
    <form method="post" action="{% url "users:billing" %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-dark">Manage Subscription</button>
    </form>
    <p class="pt-3">We are partnering with Stripe for secure subscription management.<br/>
    </p>
  {% elif user.is_trialling %}
    <p>You are currently on the <strong>{{ user.plan.name }}</strong> Trial, which expires
      in {{ user.trial_ends_at|timeuntil }}.<br/>
      Select one of the plans below to continue using our service.
    </p>
  {% else %}
    <p>You currently don't have an active subscription.<br/>
      Select one of the plans below to continue using our service.
    </p>
  {% endif %}
  <div class="pricing">
    <h2 class="pt-3 pb-3">Plans</h2>
    {% include "shared/plans.html" %}
  </div>
{% endblock %}